name: Deploy functions
on:
  workflow_dispatch:
  push:
    paths:
      - functions/**
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install Dependencies
        run: npm --prefix functions install

      - name: Restore secrets
        run: |
          echo ${{ secrets.SECRET_JSON }} > ./functions/src/secret.json
          echo ${{ secrets.FIREBASE_ADMINSDK_JSON }} > ./functions/src/firebase-adminsdk.json

      - name: Build
        run: npm --prefix functions run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: functions_lib
          path: functions/lib

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: functions_lib
          path: functions/lib

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT }}
